version: "3.9"
services:
  client:
    container_name: "project-client"
    build:
      context: "./my-chat"
    ports:
      - "3000:3000"

  server:
    container_name: "my-server"
    build:
      context: "./server"
    ports:
      - "5000:5000"
